config/routes.rb
Tostest::Application.routes.draw do
  
  
  

  get "tests/start_test"
  get "tests/question"
  get "tests/prev_question"
  get "tests/next_question"
  get "tests/check"
  post "tests/summary"
  post "tests/question"
  post "tests/check"
  post "tests/start_test"
  post "tests/after_question"
  post "tests/next_question"
  
  resources :categories
  
  resources :tests do
    resources :words
  end
  
  
  root :to => 'home#index'

end

app/models/word.rb
class Word < ActiveRecord::Base
  # attr_accesible ?
  validates :ang, :presence => true
  validates :pol1, :presence => true
  
  belongs_to :test
  has_one :word_stat
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def create
    @test = Test.find(params[:test_id])
    @word = @test.words.create(params[:word]) #creates and saves the word, and will automatically link the word so that it belongs to that particular test.
    redirect_to test_path(@test)
  end
  def destroy
    @test = Test.find(params[:test_id])
    @word = @test.words.find(params[:id])
    @word.destroy
    redirect_to test_path(@test)
  end
  
  def edit
    @test = Test.find(params[:test_id])
    @word = @test.words.find(params[:id])
  end
  
  def update
    @test = Test.find(params[:test_id])
    @word = @test.words.find(params[:id])
    
    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @test, notice: 'Word was succesfully updated.'}
      else
        format.html { render action: 'edit' }
      end
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for([@test, @word]) do |f| %>
  
<%#= form_for(@word) do |f| %>
  <div class="field">
    <%= f.label :ang %><br />
    <%= f.text_field :ang %>
  </div>
  <div class="field">
    <%= f.label :pol1 %><br />
    <%= f.text_field :pol1 %>
  </div>
  <!--
  <div class="field">
    <%#= f.label :pol2 %><br />
    <%#= f.text_field :pol2 %>
  </div>
  <div class="field">
    <%#= f.label :pol3 %><br />
    <%#= f.text_field :pol3 %>
  </div>
  <div class="field">
    <%#= f.label :opis_ang %><br />
    <%#= f.text_area :opis_ang %>
  </div>
  <div class="field">
    <%#= f.label :opis_pol %><br />
    <%#= f.text_area :opis_pol %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/_word.html.erb
  <tr>
    <td><%= word.test_id %></td>
    <td><%= word.id %></td>
    <td><%= word.ang %></td>
    <td><%= word.pol1 %></td>
    <td><%= word.pol2 %></td>
    <td><%= word.pol3 %></td>
    <td><%= word.opis_ang %></td>
    <td><%= word.opis_pol %></td>
    <% if word.word_stat == nil%>
      <td>0/0
    <% else %>
       <td><%= word.word_stat.correct %>/<%= word.word_stat.count %> 
    <% end %>
    <td><%#= link_to 'Show', [word.test, word] %></td>
    <td><%= link_to 'Edit', edit_test_word_path(word.test, word) %></td>
    <td><%= link_to 'Destroy', [word.test, word], confirm: 'Are you sure?', method: :delete %></td>
  </tr>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>